// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rakoona.core.Context;

#nullable disable

namespace rakoona.coreMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230817201909_UsuarioEnPersonaNoRequerido")]
    partial class UsuarioEnPersonaNoRequerido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Cartilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("MascotaRef")
                        .HasColumnType("int")
                        .HasColumnName("MascotaRef");

                    b.HasKey("Id");

                    b.HasIndex("MascotaRef")
                        .IsUnique();

                    b.ToTable("Cartillas", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.ClienteClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<int>("ClinicaId")
                        .HasColumnType("int")
                        .HasColumnName("ClinicaId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ClinicaId");

                    b.ToTable("ClienteClinica", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Clinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Nombre");

                    b.Property<int>("OrganizacionRef")
                        .HasColumnType("int")
                        .HasColumnName("OrganizacionRef");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionRef");

                    b.ToTable("Clinicas", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.ClinicaMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("int")
                        .HasColumnName("ClinicaId");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int")
                        .HasColumnName("MedicoRef");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("MedicoId");

                    b.ToTable("ClinicaMedicos", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comentarios");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fecha");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("MascotaRef")
                        .HasColumnType("int")
                        .HasColumnName("MascotaRef");

                    b.HasKey("Id");

                    b.HasIndex("MascotaRef");

                    b.ToTable("Citas", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartillaRef")
                        .HasColumnType("int")
                        .HasColumnName("CartillaRef");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Diagnostico");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAplicacion");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("MedicoRef")
                        .HasColumnType("int")
                        .HasColumnName("MedicoRef");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Motivo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observaciones");

                    b.HasKey("Id");

                    b.HasIndex("CartillaRef");

                    b.HasIndex("MedicoRef");

                    b.ToTable("Consultas", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDeFrecuenciaRespiratoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAplicacion");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("MascotaRef")
                        .HasColumnType("int")
                        .HasColumnName("MascotaRef");

                    b.Property<int>("Valor")
                        .HasColumnType("int")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("MascotaRef");

                    b.ToTable("MedicionDeFrecuenciaRespiratoria", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDePeso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAplicacion");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("MascotaRef")
                        .HasColumnType("int")
                        .HasColumnName("MascotaRef");

                    b.Property<double>("Valor")
                        .HasColumnType("float")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("MascotaRef");

                    b.ToTable("MedicionDePeso", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDePulso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caracteristicas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAplicacion");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("MascotaRef")
                        .HasColumnType("int")
                        .HasColumnName("MascotaRef");

                    b.Property<int>("Valor")
                        .HasColumnType("int")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("MascotaRef");

                    b.ToTable("MedicionesDePulso", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDeRitmoCardiaco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAplicacion");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("MascotaRef")
                        .HasColumnType("int")
                        .HasColumnName("MascotaRef");

                    b.Property<int>("Valor")
                        .HasColumnType("int")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("MascotaRef");

                    b.ToTable("MedicionesDeRitmoCardiaco", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDeTemperatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAplicacion");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("MascotaRef")
                        .HasColumnType("int")
                        .HasColumnName("MascotaRef");

                    b.Property<double>("Valor")
                        .HasColumnType("float")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("MascotaRef");

                    b.ToTable("MedicionesDeTemperatura", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Domicilio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CP")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("CP");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Calle");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Colonia");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Estado");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Municipio");

                    b.Property<int>("PersonaRef")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit")
                        .HasColumnName("Principal");

                    b.HasKey("Id");

                    b.HasIndex("PersonaRef");

                    b.ToTable("Domicilios", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Dosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("MedicamentoRef")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MedicamentoRef");

                    b.Property<int>("RecetaRef")
                        .HasColumnType("int")
                        .HasColumnName("RecetaRef");

                    b.HasKey("Id");

                    b.HasIndex("RecetaRef");

                    b.ToTable("Dosis", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("UserRef")
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("UserRef");

                    b.HasKey("Id");

                    b.HasIndex("UserRef")
                        .IsUnique()
                        .HasFilter("[UserRef] IS NOT NULL");

                    b.ToTable("Organizaciones", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.ClaseDeAnimales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("ClasesDeAnimales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "1ba263b9-afa7-4fd3-81c6-432372a1f283",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9704),
                            Nombre = "Mamiforo"
                        });
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DescripcionRef")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.HasKey("Id");

                    b.HasIndex("DescripcionRef");

                    b.ToTable("ColoresPorMascota", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.DescripcionFisicaDeMascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("MascotaRef")
                        .HasColumnType("int");

                    b.Property<int>("RazaRef")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MascotaRef")
                        .IsUnique();

                    b.HasIndex("RazaRef");

                    b.ToTable("DescripcionesFisicasDeMascotas", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseAnimalRef")
                        .HasColumnType("int")
                        .HasColumnName("ClaseAnimalRef");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("GeneroRef")
                        .HasColumnType("int")
                        .HasColumnName("GeneroRef");

                    b.Property<string>("NombreCientifico")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreCientifico");

                    b.Property<string>("NombreCorto")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreCorto");

                    b.Property<int>("OrdenAnimalRef")
                        .HasColumnType("int")
                        .HasColumnName("OrdenAnimalRef");

                    b.HasKey("Id");

                    b.HasIndex("ClaseAnimalRef");

                    b.HasIndex("GeneroRef");

                    b.HasIndex("OrdenAnimalRef");

                    b.ToTable("Especies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaseAnimalRef = 1,
                            ExternalId = "b0920ae7-d585-4f05-933f-bd886cefa447",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9785),
                            GeneroRef = 2,
                            NombreCorto = "Gato",
                            OrdenAnimalRef = 1
                        },
                        new
                        {
                            Id = 2,
                            ClaseAnimalRef = 1,
                            ExternalId = "aa24f47b-30cb-4b94-a4fc-08e1a2a62ab4",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9801),
                            GeneroRef = 1,
                            NombreCorto = "Perro",
                            OrdenAnimalRef = 1
                        },
                        new
                        {
                            Id = 3,
                            ClaseAnimalRef = 1,
                            ExternalId = "64a3d64e-a3f3-45b9-b3d2-ce06a7701cf6",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9818),
                            GeneroRef = 3,
                            NombreCorto = "Hurón",
                            OrdenAnimalRef = 1
                        });
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Familia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Familia", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "10b1c6bf-9b4f-4f5d-8f0d-397bda9c8652",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9726),
                            Nombre = "Canidos"
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "b2c3ef84-8bcf-418b-a780-849af9b315fe",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9730),
                            Nombre = "Félidos"
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "407a9a79-0489-417a-b7b5-9c892756ea7a",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9734),
                            Nombre = "Mustélidos"
                        });
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.GeneroAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<int>("FamiliaRef")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaRef");

                    b.ToTable("GeneroAnimal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "934c8776-fa2b-477f-92b1-940853e34928",
                            FamiliaRef = 1,
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9750),
                            Nombre = "Canis"
                        },
                        new
                        {
                            Id = 2,
                            ExternalId = "c32bda63-6c88-4208-b9ad-0ea904f2bacf",
                            FamiliaRef = 2,
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9758),
                            Nombre = "Felis"
                        },
                        new
                        {
                            Id = 3,
                            ExternalId = "dfd7f155-14be-4810-96f6-288a26243542",
                            FamiliaRef = 3,
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9768),
                            Nombre = "Mustela"
                        });
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.ImagenPorMascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("FileData");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FileName");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FileType");

                    b.Property<int>("MascotaRef")
                        .HasColumnType("int")
                        .HasColumnName("MascotaRef");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MascotaRef");

                    b.ToTable("ImagenesPorMascota", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnioNacimiento")
                        .HasColumnType("int")
                        .HasColumnName("AnioNacimiento");

                    b.Property<int?>("DiaNacimiento")
                        .HasColumnType("int")
                        .HasColumnName("DiaNacimiento");

                    b.Property<int>("DuenioRef")
                        .HasColumnType("int")
                        .HasColumnName("DuenioRef");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Genero");

                    b.Property<int?>("MesNacimiento")
                        .HasColumnType("int")
                        .HasColumnName("MesNacimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("DuenioRef");

                    b.ToTable("Macotas", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.OrdenAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("OrdenAnimal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExternalId = "468d3b4a-a64c-41d5-a69a-a25697daa0f7",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9468),
                            Nombre = "Carnívoro"
                        });
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.RazaAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EspecieRef")
                        .HasColumnType("int")
                        .HasColumnName("EspecieRef");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("NombreCientifico")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreCientifico");

                    b.Property<string>("NombreColoquial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreColoquial");

                    b.HasKey("Id");

                    b.HasIndex("EspecieRef");

                    b.ToTable("Razas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EspecieRef = 2,
                            ExternalId = "d02aecac-59ae-4f26-9ac5-f9cd6acd8896",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9849),
                            NombreColoquial = "Affenpinscher"
                        },
                        new
                        {
                            Id = 2,
                            EspecieRef = 2,
                            ExternalId = "2c389f16-baa2-4bf6-868c-5e3b0d2993e2",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9928),
                            NombreColoquial = "Afgano"
                        },
                        new
                        {
                            Id = 3,
                            EspecieRef = 2,
                            ExternalId = "6b5fceb5-93c9-4d48-8c84-691a8fd41f81",
                            FechaDeCreacion = new DateTime(2023, 8, 17, 14, 19, 9, 283, DateTimeKind.Local).AddTicks(9948),
                            NombreColoquial = "Akita"
                        });
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Personas.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("PersonaRef")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaRef")
                        .IsUnique();

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Personas.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Apellidos");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<DateTime?>("FechaDeNacimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeNacimiento");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombres");

                    b.Property<string>("UsuarioRef")
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("UsuarioRef");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioRef")
                        .IsUnique()
                        .HasFilter("[UsuarioRef] IS NOT NULL");

                    b.ToTable("Personas", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.PlanDeVacunacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Caducidad")
                        .HasColumnType("datetime2")
                        .HasColumnName("Caducidad");

                    b.Property<int>("CartillaRef")
                        .HasColumnType("int")
                        .HasColumnName("CartillaRef");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaAplicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAplicacion");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<string>("Laboratorio")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Laboratorio");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Lote");

                    b.Property<int>("MedicoRef")
                        .HasColumnType("int")
                        .HasColumnName("MedicoRef");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("CartillaRef");

                    b.HasIndex("MedicoRef");

                    b.ToTable("Vacunaciones", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Receta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultaRef")
                        .HasColumnType("int");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.HasKey("Id");

                    b.ToTable("Recetas", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Seguridad.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NormalizedEmail");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("NormalizedUserName");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.TiposDeContacto.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ContactType");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("ExternalId");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaDeCreacion");

                    b.Property<int>("PersonaRef")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("PersonaRef");

                    b.ToTable("InformacionDeContacto", (string)null);

                    b.HasDiscriminator<string>("ContactType").HasValue("Contacto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Personas.Cliente", b =>
                {
                    b.HasBaseType("rakoona.core.Entities.Models.Personas.Persona");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.TiposDeContacto.Celular", b =>
                {
                    b.HasBaseType("rakoona.core.Entities.Models.TiposDeContacto.Contacto");

                    b.HasDiscriminator().HasValue("Celular");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.TiposDeContacto.Email", b =>
                {
                    b.HasBaseType("rakoona.core.Entities.Models.TiposDeContacto.Contacto");

                    b.HasDiscriminator().HasValue("Email");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Seguridad.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Seguridad.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rakoona.core.Entities.Models.Seguridad.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Seguridad.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Cartilla", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Mascota", "Mascota")
                        .WithOne("Cartilla")
                        .HasForeignKey("rakoona.core.Entities.Models.Cartilla", "MascotaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.ClienteClinica", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Personas.Cliente", "Cliente")
                        .WithMany("ClienteClinicas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rakoona.core.Entities.Models.Clinica", "Clinica")
                        .WithMany("ClienteClinicas")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Clinica", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Organizacion", "Organizacion")
                        .WithMany("Clinicas")
                        .HasForeignKey("OrganizacionRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.ClinicaMedico", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Clinica", "Clinica")
                        .WithMany("ClinicaMedicos")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("rakoona.core.Entities.Models.Personas.Medico", "Medico")
                        .WithMany("ClinicaMedicos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Cita", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Mascota", "Mascota")
                        .WithMany("Citas")
                        .HasForeignKey("MascotaRef")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Consulta", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Cartilla", "Cartilla")
                        .WithMany("Consultas")
                        .HasForeignKey("CartillaRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rakoona.core.Entities.Models.Personas.Medico", "Medico")
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoRef")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cartilla");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDeFrecuenciaRespiratoria", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Consultas.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId");

                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Mascota", "Mascota")
                        .WithMany("MedicionesDeFrecuenciaRespiratoria")
                        .HasForeignKey("MascotaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDePeso", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Consultas.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId");

                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Mascota", "Mascota")
                        .WithMany("MedicionesDePeso")
                        .HasForeignKey("MascotaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDePulso", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Consultas.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId");

                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Mascota", "Mascota")
                        .WithMany("MedicionesDePulso")
                        .HasForeignKey("MascotaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDeRitmoCardiaco", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Consultas.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId");

                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Mascota", "Mascota")
                        .WithMany("MedicionesDeRitmoCardiaco")
                        .HasForeignKey("MascotaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Consultas.Mediciones.MedicionDeTemperatura", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Consultas.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId");

                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Mascota", "Mascota")
                        .WithMany("MedicionesDeTemperatura")
                        .HasForeignKey("MascotaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Domicilio", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Personas.Persona", "Persona")
                        .WithMany("Domicilios")
                        .HasForeignKey("PersonaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Dosis", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Receta", "Receta")
                        .WithMany("Dosis")
                        .HasForeignKey("RecetaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Organizacion", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Seguridad.User", "Usuario")
                        .WithOne("Organizacion")
                        .HasForeignKey("rakoona.core.Entities.Models.Organizacion", "UserRef")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Color", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Pacientes.DescripcionFisicaDeMascota", "Descripcion")
                        .WithMany("Colores")
                        .HasForeignKey("DescripcionRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descripcion");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.DescripcionFisicaDeMascota", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Mascota", "Mascota")
                        .WithOne("Descripcion")
                        .HasForeignKey("rakoona.core.Entities.Models.Pacientes.DescripcionFisicaDeMascota", "MascotaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rakoona.core.Entities.Models.Pacientes.RazaAnimal", "Raza")
                        .WithMany("DescipcionesFisicasDeMascota")
                        .HasForeignKey("RazaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");

                    b.Navigation("Raza");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Especie", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Pacientes.ClaseDeAnimales", "ClaseAnimal")
                        .WithMany("Especies")
                        .HasForeignKey("ClaseAnimalRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rakoona.core.Entities.Models.Pacientes.GeneroAnimal", "Genero")
                        .WithMany("Especies")
                        .HasForeignKey("GeneroRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rakoona.core.Entities.Models.Pacientes.OrdenAnimal", "Orden")
                        .WithMany("Especies")
                        .HasForeignKey("OrdenAnimalRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClaseAnimal");

                    b.Navigation("Genero");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.GeneroAnimal", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Familia", "Familia")
                        .WithMany("Generos")
                        .HasForeignKey("FamiliaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.ImagenPorMascota", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Mascota", "Mascota")
                        .WithMany("Imagenes")
                        .HasForeignKey("MascotaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Mascota", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Personas.Cliente", "Duenio")
                        .WithMany("Mascotas")
                        .HasForeignKey("DuenioRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duenio");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.RazaAnimal", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Pacientes.Especie", "Especie")
                        .WithMany("Razas")
                        .HasForeignKey("EspecieRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Personas.Medico", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Personas.Persona", "PersonaInfo")
                        .WithOne("MedicoInfo")
                        .HasForeignKey("rakoona.core.Entities.Models.Personas.Medico", "PersonaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonaInfo");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Personas.Persona", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Seguridad.User", "User")
                        .WithOne("Persona")
                        .HasForeignKey("rakoona.core.Entities.Models.Personas.Persona", "UsuarioRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.PlanDeVacunacion", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Cartilla", "Cartilla")
                        .WithMany("PlanesDeVacunacion")
                        .HasForeignKey("CartillaRef")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("rakoona.core.Entities.Models.Personas.Medico", "Medico")
                        .WithMany("Vacunas")
                        .HasForeignKey("MedicoRef")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cartilla");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.TiposDeContacto.Contacto", b =>
                {
                    b.HasOne("rakoona.core.Entities.Models.Personas.Persona", "Persona")
                        .WithMany("InformacionDeContacto")
                        .HasForeignKey("PersonaRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Cartilla", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("PlanesDeVacunacion");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Clinica", b =>
                {
                    b.Navigation("ClienteClinicas");

                    b.Navigation("ClinicaMedicos");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Organizacion", b =>
                {
                    b.Navigation("Clinicas");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.ClaseDeAnimales", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.DescripcionFisicaDeMascota", b =>
                {
                    b.Navigation("Colores");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Especie", b =>
                {
                    b.Navigation("Razas");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Familia", b =>
                {
                    b.Navigation("Generos");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.GeneroAnimal", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.Mascota", b =>
                {
                    b.Navigation("Cartilla")
                        .IsRequired();

                    b.Navigation("Citas");

                    b.Navigation("Descripcion")
                        .IsRequired();

                    b.Navigation("Imagenes");

                    b.Navigation("MedicionesDeFrecuenciaRespiratoria");

                    b.Navigation("MedicionesDePeso");

                    b.Navigation("MedicionesDePulso");

                    b.Navigation("MedicionesDeRitmoCardiaco");

                    b.Navigation("MedicionesDeTemperatura");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.OrdenAnimal", b =>
                {
                    b.Navigation("Especies");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Pacientes.RazaAnimal", b =>
                {
                    b.Navigation("DescipcionesFisicasDeMascota");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Personas.Medico", b =>
                {
                    b.Navigation("ClinicaMedicos");

                    b.Navigation("Consultas");

                    b.Navigation("Vacunas");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Personas.Persona", b =>
                {
                    b.Navigation("Domicilios");

                    b.Navigation("InformacionDeContacto");

                    b.Navigation("MedicoInfo");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Receta", b =>
                {
                    b.Navigation("Dosis");
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Seguridad.User", b =>
                {
                    b.Navigation("Organizacion")
                        .IsRequired();

                    b.Navigation("Persona")
                        .IsRequired();
                });

            modelBuilder.Entity("rakoona.core.Entities.Models.Personas.Cliente", b =>
                {
                    b.Navigation("ClienteClinicas");

                    b.Navigation("Mascotas");
                });
#pragma warning restore 612, 618
        }
    }
}
